import type { Skill } from '../types'

const MONEY = '\\$\\s?\\d{1,3}(?:,\\d{3})*(?:\\.\\d{2})?'
const DATE =
  '\\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\\.? \\d{1,2}(?:st|nd|rd|th)?(?:,? \\d{4})?\\b|\\b\\d{1,2}/\\d{1,2}(?:/\\d{2,4})?\\b'

/** Watchers for the Life & home profiles: benefits, medications, the home, activities, immigration, statements, and orders. */
export const LIFE_SKILLS: Skill[] = [
  {
    id: 'l-benefits',
    name: 'Benefits & coverage notices',
    icon: '🏛️',
    description: 'Watches Medicare, Social Security, VA, unemployment, and insurance letters for dates you must act by.',
    defaultFor: ['retiree', 'caregiver', 'jobseeker', 'military', 'newcomer'],
    match: [
      '\\bmedicare\\b',
      '\\bmedicaid\\b',
      'social security',
      '\\bssa\\.gov\\b',
      'unemployment (?:benefits|claim|insurance)',
      'weekly (?:certification|claim)',
      '\\bcobra\\b',
      '\\bva (?:claim|benefits|disability|decision)\\b',
      '\\btricare\\b',
      'pension (?:statement|payment|election)',
      'open enrollment',
      'enrollment period',
      'benefit(?:s)? (?:statement|notice|decision|determination|verification)',
      'explanation of benefits',
      'coverage (?:ends|will end|renewal|change)',
      'eligibility (?:notice|review|redetermination)'
    ],
    senderMatch: ['@ssa\\.gov$', '@medicare\\.gov$', '@va\\.gov$', '@cms\\.hhs\\.gov$', '\\.gov$'],
    extractors: [
      { field: 'dueDate', pattern: `(?:by|before|no later than|respond by|deadline(?: is)?|ends?(?: on)?|due) (${DATE})`, flags: 'i' },
      { field: 'amount', pattern: `(${MONEY})`, flags: 'i' },
      { field: 'claimNumber', pattern: '(?:claim|case|reference|confirmation)\\s?(?:number|no\\.?|#)[:\\s]+([A-Z0-9-]{5,20})', flags: 'i' }
    ],
    urgentWhen: ['final notice', 'will (?:end|terminate|lapse|stop)', 'action required', 'respond (?:by|within)', 'denied', 'overpayment', 'appeal (?:deadline|by)', 'last day to'],
    minImportance: 2,
    forceCategory: 'personal',
    lineTemplate: '{subject} — by {dueDate} {amount} ({from})',
    sectionTitle: 'Benefits & coverage',
    promptHint: 'Benefit and coverage letters often hide a deadline in the body; pull the exact date and say plainly what happens if it is missed.'
  },
  {
    id: 'l-medications',
    name: 'Prescriptions & pharmacy',
    icon: '💊',
    description: 'Catches refill reminders, ready-for-pickup notices, and prior-authorization holds before anyone runs out.',
    defaultFor: ['retiree', 'caregiver', 'parent'],
    match: [
      'ready for pickup',
      'ready (?:to|for) pick ?up',
      'refill (?:ready|due|reminder|request|approved|denied)',
      'prescription (?:is ready|has been filled|refill|reminder|status)',
      'auto-?refill',
      '90-day supply',
      'prior authorization',
      'medication reminder',
      'time to refill',
      'pharmacy (?:notice|pickup|order|reminder)',
      'mail[- ]order pharmacy',
      'pill pack'
    ],
    senderMatch: ['cvs', 'walgreens', 'riteaid', 'expressscripts', 'express-scripts', 'optumrx', 'caremark', 'pillpack', 'amazon pharmacy', 'costcopharmacy'],
    extractors: [
      { field: 'when', pattern: `(?:by|until|before|on|pick ?up by|ready(?: on| by)?|due) (${DATE})`, flags: 'i' },
      { field: 'pharmacy', pattern: '(?:at|from) ((?:cvs|walgreens|rite aid|walmart|costco|kroger|safeway|publix|express scripts|optumrx|caremark)(?: pharmacy)?)', flags: 'i' },
      { field: 'rxNumber', pattern: '\\brx\\s?#?\\s?(\\d{6,10})\\b', flags: 'i' }
    ],
    urgentWhen: ['will be returned to stock', 'last day', 'out of refills', 'prior authorization (?:required|needed|denied)', 'denied', 'expires? (?:today|tomorrow)', 'urgent'],
    minImportance: 2,
    forceCategory: 'personal',
    lineTemplate: '{subject} — {when} at {pharmacy} ({from})',
    sectionTitle: 'Prescriptions & pharmacy',
    promptHint: 'Treat pickup deadlines and out-of-refills notices as actionable today; never repeat drug names or dosages beyond what the subject says.'
  },
  {
    id: 'l-home',
    name: 'Home & household notices',
    icon: '🏠',
    description: 'Tracks HOA and landlord notices, lease dates, utility alerts, warranty claims, and repair visits.',
    defaultFor: ['homeowner', 'investor', 'newcomer'],
    match: [
      '\\bhoa\\b',
      'homeowners association',
      'condo association',
      'lease (?:renewal|expires|expiration|ends|agreement)',
      'rent (?:is due|due|increase|reminder|payment)',
      'move[- ](?:in|out) (?:date|inspection|checklist)',
      'maintenance (?:request|visit|scheduled|window)',
      'service (?:call|visit|window|technician) (?:is )?(?:scheduled|confirmed)',
      'technician (?:will arrive|is scheduled|arrival window)',
      'home warranty',
      'warranty claim',
      'insurance claim (?:number|update|adjuster)',
      'utility (?:shutoff|shut-off|disconnect|outage|notice)',
      'water (?:shutoff|shut-off|main|leak)',
      'property tax',
      'mortgage (?:statement|payment|escrow)',
      'inspection (?:scheduled|notice|required)',
      'violation notice',
      'pest control (?:visit|scheduled|appointment)'
    ],
    extractors: [
      { field: 'when', pattern: `(?:on|by|before|between|scheduled for|due|window) (${DATE}[^\\n.]{0,25}?(?:\\d{1,2}(?::\\d{2})?\\s?(?:am|pm))?)`, flags: 'i' },
      { field: 'amount', pattern: `(${MONEY})`, flags: 'i' },
      { field: 'claimNumber', pattern: '(?:claim|ticket|work order|reference)\\s?(?:number|no\\.?|#)[:\\s]+([A-Z0-9-]{4,20})', flags: 'i' }
    ],
    urgentWhen: ['shutoff', 'shut-off', 'disconnect', 'leak', 'violation', 'eviction', 'past due', 'final notice', 'today', 'tomorrow', 'emergency'],
    minImportance: 2,
    forceCategory: 'personal',
    lineTemplate: '{subject} — {when} {amount} ({from})',
    sectionTitle: 'Home & household',
    promptHint: 'Home notices with a visit window or a payment date go in the deadlines list; shutoff, leak, and violation notices are always issues.'
  },
  {
    id: 'l-activities',
    name: 'Activities & signups',
    icon: '⚽',
    description: 'Gathers practices, games, camps, rehearsals, and signup deadlines into one schedule.',
    defaultFor: ['parent', 'volunteer'],
    match: [
      'practice (?:is|has been|will be|schedule|cancel|moved|tonight|tomorrow)',
      'game (?:day|time|schedule|cancel|rescheduled)',
      '\\bmatch (?:day|time|schedule)\\b',
      'rehearsal',
      'tournament',
      'camp (?:registration|signup|sign-up|session|starts|pickup|drop-?off)',
      'registration (?:is open|opens|closes|deadline|confirmed|reminder)',
      'sign[- ]?ups? (?:open|close|deadline|reminder)',
      'signupgenius',
      'roster',
      'season (?:starts|schedule|kickoff|opener)',
      'tryouts?',
      'volunteer (?:shift|slot|needed|signup)',
      'uniform (?:pickup|order|fitting)',
      'snack (?:duty|schedule|sign)',
      'carpool'
    ],
    senderMatch: ['teamsnap', 'sportsengine', 'leagueapps', 'signupgenius', 'classdojo', 'parentsquare'],
    extractors: [
      { field: 'when', pattern: `(${DATE}[^\\n.]{0,25}?(?:\\d{1,2}(?::\\d{2})?\\s?(?:am|pm))?|(?:mon|tues|wednes|thurs|fri|satur|sun)day[^\\n.]{0,15}?\\d{1,2}(?::\\d{2})?\\s?(?:am|pm))`, flags: 'i' },
      { field: 'location', pattern: '(?:at|@|location:) ([A-Z][A-Za-z0-9 .&\'-]{3,40}(?:field|park|gym|center|school|arena|rink|pool|court|complex|stadium)\\b)', flags: '' }
    ],
    urgentWhen: ['cancel', 'rain ?out', 'moved to', 'time change', 'today', 'tonight', 'tomorrow', 'closes (?:today|tomorrow|soon)', 'spots? (?:left|remaining)', 'waitlist'],
    minImportance: 2,
    forceCategory: 'personal',
    lineTemplate: '{subject} — {when} {location} ({from})',
    sectionTitle: 'Activities & signups',
    promptHint: 'Every practice, game, camp, or signup date is a deadline; a cancelled or moved session is an issue that changes today\'s plan.'
  },
  {
    id: 'l-immigration',
    name: 'Immigration, visas & passports',
    icon: '🛂',
    description: 'Follows USCIS case updates, biometrics and interview dates, visa applications, and passport expirations.',
    defaultFor: ['newcomer', 'traveler'],
    match: [
      '\\buscis\\b',
      'case status',
      'receipt number',
      'biometrics',
      'request for evidence',
      '\\brfe\\b',
      'notice of action',
      '\\bi-\\d{3}[a-z]?\\b',
      '\\bn-400\\b',
      'green card',
      'permanent resident',
      'naturalization',
      'oath ceremony',
      'work (?:permit|authorization)',
      'visa (?:application|appointment|interview|approved|denied|status|expires|stamping|extension)',
      'e-?visa',
      'residence permit',
      'passport (?:renewal|expires|expiration|application|ready|pickup)',
      'consulate',
      'embassy',
      'immigration (?:lawyer|attorney|interview|appointment|court)',
      'i-94'
    ],
    senderMatch: ['@uscis\\.dhs\\.gov$', '@state\\.gov$', '@cbp\\.dhs\\.gov$', 'travel\\.state\\.gov', 'ustraveldocs'],
    extractors: [
      { field: 'when', pattern: `(?:on|by|before|scheduled for|appointment(?: is| date)?:?|interview(?: is| date)?:?|due|expires?(?: on)?|deadline:?) (${DATE}[^\\n.]{0,25}?(?:\\d{1,2}(?::\\d{2})?\\s?(?:am|pm))?)`, flags: 'i' },
      { field: 'receipt', pattern: '\\b([A-Z]{3}\\d{10})\\b', flags: '' },
      { field: 'form', pattern: '\\b(i-\\d{3}[a-z]?|n-\\d{3}|ds-\\d{3,4})\\b', flags: 'i' }
    ],
    urgentWhen: ['request for evidence', '\\brfe\\b', 'denied', 'denial', 'rescheduled', 'missed appointment', 'expires? (?:in|within|on|soon)', 'respond (?:by|within)', 'deadline', 'notice of intent', 'court date', 'failure to'],
    minImportance: 3,
    forceCategory: 'personal',
    lineTemplate: '{subject} — {form} {receipt} · {when} ({from})',
    sectionTitle: 'Immigration & visas',
    promptHint: 'Immigration and visa mail is always high priority; give the appointment or response date exactly and explain the form or acronym in plain words.'
  },
  {
    id: 'l-statements',
    name: 'Statements, tax forms & dividends',
    icon: '🧾',
    description: 'Notes brokerage and retirement statements, tax forms, dividends, and account alerts as they arrive.',
    defaultFor: ['investor', 'retiree'],
    match: [
      'statement (?:is|are) (?:ready|available|now available)',
      'monthly statement',
      'quarterly statement',
      'annual statement',
      'tax (?:form|document|statement)s? (?:is|are|now) (?:ready|available)',
      '\\b1099(?:-[a-z]+)?\\b',
      '\\bw-2\\b',
      'schedule k-1',
      'form 5498',
      'dividend',
      'capital gains? distribution',
      'trade confirmation',
      'order (?:executed|filled)',
      'transfer (?:complete|initiated|failed)',
      'margin call',
      'required minimum distribution',
      '\\brmd\\b',
      'contribution (?:confirmed|received|limit)',
      'rental (?:payment|income) received',
      'estimated tax'
    ],
    senderMatch: ['schwab', 'fidelity', 'vanguard', 'robinhood', 'etrade', 'interactivebrokers', 'coinbase', 'wealthfront', 'betterment', 'tdameritrade', 'merrill', 'ally', 'sofi', 'turbotax', 'irs\\.gov'],
    extractors: [
      { field: 'amount', pattern: `(${MONEY})`, flags: 'i' },
      { field: 'dueDate', pattern: `(?:due|by|before|deadline|no later than|pay by) (${DATE})`, flags: 'i' },
      { field: 'account', pattern: '(?:account|acct\\.?)\\s?(?:ending(?: in)?|#|number)?[:\\s]*(?:x+|\\*+)?(\\d{4})\\b', flags: 'i' }
    ],
    urgentWhen: ['margin call', 'failed', 'returned', 'suspicious', 'unusual activity', 'verify your', 'locked', 'due (?:today|tomorrow)', 'deadline', 'past due'],
    minImportance: 1,
    forceCategory: 'personal',
    lineTemplate: '{subject} — {amount} {dueDate} ({from})',
    sectionTitle: 'Statements & tax forms',
    promptHint: 'Statements are informational unless they show a failed transfer, a security alert, or a tax deadline; tax forms should be listed so they are not lost at filing time.'
  },
  {
    id: 'l-orders',
    name: 'Orders, PCS & deployment',
    icon: '🎖️',
    description: 'Watches military orders, PCS moves, report dates, deployment and unit family notices, and housing dates.',
    defaultFor: ['military'],
    match: [
      '\\bpcs\\b',
      'permanent change of station',
      '\\borders (?:have been|were|are) (?:cut|issued|published|amended)',
      'report (?:date|no later than|nlt)',
      '\\brnlt\\b',
      'household goods',
      '\\bhhg\\b',
      'deployment',
      'deploy(?:ing|ed)\\b',
      'homecoming',
      'family readiness',
      '\\bfrg\\b',
      'ombudsman',
      'housing (?:office|assignment|move-in|move-out|inspection)',
      'base housing',
      '\\bdeers\\b',
      'id card (?:renewal|appointment|expires)',
      '\\btdy\\b',
      'drill weekend',
      'leave (?:approved|request|form)',
      'terminal leave',
      'dd-?214',
      'sponsor (?:assigned|information|welcome)'
    ],
    senderMatch: ['\\.mil$', 'militaryonesource', 'dfas', 'tricare', 'va\\.gov'],
    extractors: [
      { field: 'when', pattern: `(?:report(?: date| by| nlt| no later than)?|nlt|on|by|before|between|scheduled for|effective|depart(?:ing|ure)?(?: on)?|return(?:ing)?(?: on)?) (${DATE})`, flags: 'i' },
      { field: 'station', pattern: '\\b((?:fort|camp|naval (?:base|station|air station)|joint base|marine corps base|(?:[A-Z][a-z]+ )?air force base|nas|jb|mcb|mcas)\\s[A-Z][A-Za-z.\\- ]{2,30})', flags: '' },
      { field: 'orderNumber', pattern: '(?:order|orders)\\s?(?:number|no\\.?|#)[:\\s]+([A-Z0-9-]{4,20})', flags: 'i' }
    ],
    urgentWhen: ['amended', 'report (?:date|nlt)', 'recall', 'short[- ]notice', 'immediately', 'red cross message', 'emergency', 'casualty', 'curtailed', 'today', 'tomorrow'],
    minImportance: 2,
    forceCategory: 'personal',
    lineTemplate: '{subject} — {when} {station} ({from})',
    sectionTitle: 'Orders & family readiness',
    promptHint: 'Orders, report dates, and move windows are hard deadlines; family readiness and Red Cross messages are always issues. Spell out acronyms (PCS, HHG, RNLT, DEERS) in plain words.'
  }
]
