import type { Skill } from '../types'

const MONEY = '\\$\\s?\\d{1,3}(?:,\\d{3})*(?:\\.\\d{2})?'
const DATE =
  '\\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\\.? \\d{1,2}(?:st|nd|rd|th)?(?:,? \\d{4})?\\b|\\b\\d{1,2}/\\d{1,2}(?:/\\d{2,4})?\\b'
const STREET =
  '(\\d{2,6} [A-Z][a-zA-Z]+(?: [A-Z][a-zA-Z]+)? (?:St|Street|Ave|Avenue|Rd|Road|Dr|Drive|Ln|Lane|Blvd|Ct|Court|Way|Pl|Place|Cir|Circle|Hwy)\\b\\.?)'

/** Watchers for trades, field, and property people. */
export const TRADES_SKILLS: Skill[] = [
  {
    id: 't-permits',
    name: 'Permits & inspections',
    icon: '📋',
    description: 'Watches permit approvals, inspection appointments and results, and correction notices from the building department.',
    defaultFor: ['contractor', 'tradesperson', 'landlord'],
    match: [
      'building permit',
      'permit (?:application|approved|issued|expir|renewal|fee|number|#|is ready)',
      '(?:framing|footing|foundation|rough[- ]in|final|electrical|plumbing|mechanical|hvac|insulation|drywall|fire|hud|hqs|housing|rental|annual) inspection',
      'inspection (?:passed|failed|scheduled|result|request|report|window)',
      'inspector (?:will|is|has|scheduled|coming|assigned|notes)',
      'certificate of occupancy',
      'plan (?:check|review) (?:comments|approved|complete)',
      'code (?:violation|correction|enforcement)',
      'correction notice',
      'stop[- ]work order',
      're-?inspection'
    ],
    extractors: [
      { field: 'permit', pattern: 'permit\\s?(?:no\\.?|number|#)\\s?:?\\s?([A-Z0-9-]{4,})', flags: 'i' },
      { field: 'address', pattern: STREET, flags: '' },
      { field: 'when', pattern: `(?:scheduled|inspection|reinspection|re-inspection|expires?|expiring|due) (?:is |for |on |by )?(${DATE}|today|tomorrow)`, flags: 'i' }
    ],
    urgentWhen: ['failed', 'stop[- ]work', 'correction notice', 'code violation', 'expir(?:es|ing) (?:today|tomorrow|this week)', 'inspection (?:is )?(?:today|tomorrow)', 'reschedul'],
    minImportance: 2,
    forceCategory: 'work',
    lineTemplate: '{subject} — {address} permit {permit} · {when} ({from})',
    sectionTitle: 'Permits & inspections',
    promptHint: 'Inspection appointments and permit expirations always go in the deadlines list; a failed inspection or correction notice is an urgent issue.'
  },
  {
    id: 't-jobs',
    name: 'Jobs, estimates & change orders',
    icon: '🧾',
    description: 'Follows estimates, bids, change orders, deposits, punch lists and final payments for each job.',
    defaultFor: ['contractor', 'tradesperson', 'homeservices', 'mechanic'],
    match: [
      'estimate (?:approved|accepted|declined|signed|request|attached)',
      'change order',
      'punch ?list',
      'scope of work',
      'bid (?:due|accepted|awarded|package|opening)',
      'lien waiver',
      'draw request',
      'pay app(?:lication)?',
      'retainage',
      'deposit (?:received|due|for the job)',
      'job (?:is )?(?:complete|done|scheduled|started|finished)',
      'walk-?through',
      'final payment',
      'progress payment',
      'materials? (?:delivery|delivered|backorder|on order|arrived)',
      'start date for (?:the|your)',
      'crew (?:will|is) (?:arriv|start)'
    ],
    extractors: [
      { field: 'amount', pattern: `(${MONEY})`, flags: 'i' },
      { field: 'address', pattern: STREET, flags: '' },
      { field: 'dueDate', pattern: `(?:due|by|before|start(?:s|ing)? (?:on)?|scheduled for|deadline) (?:on )?(${DATE})`, flags: 'i' }
    ],
    urgentWhen: ['change order (?:needs|awaiting|pending|requires) (?:approval|signature)', 'bid (?:is )?due', 'stop[- ]work', 'not (?:been )?paid', 'past due', 'delayed', 'backorder', 'unhappy', 'redo', 'damage'],
    minImportance: 2,
    forceCategory: 'work',
    lineTemplate: '{subject} — {address} {amount} due {dueDate} ({from})',
    sectionTitle: 'Jobs & estimates',
    promptHint: 'Treat each job address or customer as its own entity; a change order or estimate waiting on a signature is an actionable issue with the amount and date extracted exactly.'
  },
  {
    id: 't-tenants',
    name: 'Tenants & rentals',
    icon: '🔑',
    description: 'Gathers tenant maintenance requests, rent payments, lease renewals and notices for each unit.',
    defaultFor: ['landlord'],
    match: [
      'maintenance request',
      'repair request',
      '\\btenants?\\b',
      'rent (?:is )?(?:due|late|past due|received|payment|increase|reminder)',
      'lease (?:renewal|expir|signing|violation|agreement)',
      'notice to vacate',
      'move-?(?:in|out)',
      'security deposit',
      'rental application',
      'eviction',
      'pay or quit',
      'late fee',
      'hud inspection',
      'section 8',
      'housing authority',
      '\\bunit \\d{1,4}\\b',
      'vacan(?:t|cy)',
      'showing (?:the|of the) unit'
    ],
    extractors: [
      { field: 'unit', pattern: '\\b(?:unit|apt\\.?|apartment|suite|#)\\s?([0-9]{1,4}[a-z]?)\\b', flags: 'i' },
      { field: 'address', pattern: STREET, flags: '' },
      { field: 'amount', pattern: `(${MONEY})`, flags: 'i' },
      { field: 'dueDate', pattern: `(?:due|by|before|expires?|expiring|renew(?:al|s)? by|vacate by|move(?:s|-in|-out)? (?:on|date)) (?:on |is )?(${DATE})`, flags: 'i' }
    ],
    urgentWhen: ['no (?:heat|hot water|water|power|electricity)', '\\bleak', 'flood', 'smell(?:s|ing)? (?:of )?gas', 'gas smell', 'lock(?:ed)? out', 'emergency', 'eviction', 'pay or quit', 'notice to vacate', 'past due', 'late rent', 'not (?:been )?paid', 'broken (?:window|lock|door)', 'carbon monoxide', 'sewage'],
    minImportance: 2,
    forceCategory: 'work',
    lineTemplate: '{subject} — unit {unit} {address} {amount} due {dueDate} ({from})',
    sectionTitle: 'Tenants & rentals',
    promptHint: 'Name each entity by address and unit number; emergency maintenance (no heat, leaks, lockouts) and legal notices are urgent issues, and rent or lease dates go in the deadlines list.'
  },
  {
    id: 't-loads',
    name: 'Loads & dispatch',
    icon: '🛣️',
    description: 'Tracks load offers, pickup and delivery appointments, dispatch notes, DOT paperwork and hours-of-service notices.',
    defaultFor: ['driver'],
    match: [
      'load (?:number|#|confirmation|tender|offer|assigned|board|cancel)',
      'rate con(?:firmation)?',
      '\\bdispatch',
      'bill of lading',
      '\\bbol\\b',
      'proof of delivery',
      '\\bpod\\b',
      'pickup (?:number|appointment|window|time)',
      'delivery (?:appointment|window)',
      'dock appointment',
      'hours of service',
      '\\beld\\b',
      'log(?:book)? violation',
      'dot (?:inspection|physical|medical card|audit)',
      'medical card',
      'cdl (?:renewal|expir)',
      'detention',
      'lumper',
      'layover',
      'fuel (?:card|advance)',
      'route (?:assigned|sheet|manifest)',
      'settlement (?:statement|sheet)',
      'trip (?:sheet|pay)'
    ],
    extractors: [
      { field: 'loadNumber', pattern: '(?:load|ref(?:erence)?|pro|order)\\s?(?:no\\.?|number|#)\\s?:?\\s?([A-Z0-9-]{4,})', flags: 'i' },
      { field: 'amount', pattern: `(${MONEY})`, flags: 'i' },
      { field: 'when', pattern: `(?:pickup|pick up|pick-up|delivery|deliver by|delivers?|appointment|appt|due)[: ]+(?:on |is |at |by )?(${DATE}|today|tomorrow)`, flags: 'i' },
      { field: 'dueDate', pattern: `(?:expires?|expiring|renew(?:al)? by|due) (?:on |by )?(${DATE})`, flags: 'i' }
    ],
    urgentWhen: ['load (?:cancel|fell through|has been cancel)', 'reschedul', 'late (?:pickup|delivery)', 'detention', 'hos violation', 'out of hours', 'log(?:book)? violation', 'medical card (?:expir|due|renew)', 'cdl (?:expir|suspend)', 'breakdown', 'broke down', 'roadside inspection', 'out of service', 'appointment (?:is )?(?:today|tomorrow)'],
    minImportance: 2,
    forceCategory: 'work',
    lineTemplate: '{subject} — load {loadNumber} {when} {amount} ({from})',
    sectionTitle: 'Loads & dispatch',
    promptHint: 'Track each load by its number or origin-to-destination; pickup and delivery appointments are deadlines, and hours-of-service, medical-card, or CDL problems are urgent.'
  },
  {
    id: 't-parts',
    name: 'Parts & vehicle service',
    icon: '🔩',
    description: 'Spots parts orders and backorders, repair orders, service reminders, recalls and vehicles ready for pickup.',
    defaultFor: ['mechanic', 'driver', 'farmer', 'warehouse'],
    match: [
      'parts? (?:order|quote|invoice|on order|arrived|backorder|delivery|return|is in|are in)',
      'core (?:charge|return)',
      'repair order',
      '\\bro\\s?#\\s?\\d{3,}',
      'estimate approval',
      'approve (?:the )?(?:repair|estimate|work)',
      'vehicle (?:is )?ready',
      'your (?:car|truck|vehicle|unit) is ready',
      'oil change',
      'tire rotation',
      'brake (?:pads|job|service)',
      'check engine',
      'pm (?:due|service|is due)',
      'preventive maintenance',
      'recall notice',
      'safety recall',
      'warranty claim',
      'tow(?:ed|ing)? in',
      'service (?:is )?due',
      'equipment (?:is )?down',
      'unit (?:is )?down'
    ],
    extractors: [
      { field: 'ro', pattern: '\\bro\\s?#?\\s?(\\d{4,8})\\b', flags: 'i' },
      { field: 'partNumber', pattern: 'part\\s?(?:no\\.?|number|#)\\s?:?\\s?([A-Z0-9-]{4,})', flags: 'i' },
      { field: 'amount', pattern: `(${MONEY})`, flags: 'i' },
      { field: 'when', pattern: `(?:arriv|deliver|expect|ready|eta|due)[a-z]*[: ]+(?:by |on |for )?(${DATE}|today|tomorrow)`, flags: 'i' }
    ],
    urgentWhen: ['backorder', 'recall', 'customer (?:is )?waiting', 'waiter', 'wrong part', 'core (?:due|overdue)', 'vehicle down', 'truck down', 'unit down', 'equipment down', 'out of service', 'safety (?:issue|concern)'],
    minImportance: 2,
    forceCategory: 'work',
    lineTemplate: '{subject} — RO {ro} part {partNumber} {amount} arriving {when} ({from})',
    sectionTitle: 'Parts & vehicle service',
    promptHint: 'Backordered or wrong parts and vehicles out of service are urgent issues; extract the part or repair-order number and the arrival date exactly.'
  },
  {
    id: 't-shifts',
    name: 'Shifts, overtime & call-outs',
    icon: '🕐',
    description: 'Collects shift schedules, bids and trades, overtime and hold-overs, and call-outs that leave a shift uncovered.',
    defaultFor: ['firstresponder', 'warehouse', 'driver', 'homeservices'],
    match: [
      'shift (?:bid|trade|swap|change|schedule|coverage|open|assignment)',
      'open shifts?',
      'overtime',
      '\\bot\\b (?:list|sign|available|mandatory|opportunit)',
      'mandatory (?:overtime|ot)',
      'held over',
      'hold-?over',
      'hire-?back',
      'call-?(?:out|off)s?',
      'called (?:out|off|in sick)',
      'no-?call no-?show',
      'schedule (?:posted|for next week|change|is out)',
      'time ?off request',
      'pto request',
      'vacation request',
      'cover(?:ing)? (?:my|your|the|a) shift',
      'kelly day',
      'shift (?:starts?|begins) at',
      'roster',
      'crew (?:schedule|assignment)'
    ],
    extractors: [
      {
        field: 'when',
        pattern: `(${DATE}[^\\n.]{0,20}?\\d{1,2}(?::\\d{2})?\\s?(?:am|pm)?|\\d{1,2}(?::\\d{2})?\\s?(?:am|pm)|\\b[0-2]\\d[0-5]\\d ?hrs\\b)`,
        flags: 'i'
      },
      { field: 'dueDate', pattern: `(?:respond|reply|sign up|bid|submit) by (${DATE})`, flags: 'i' }
    ],
    urgentWhen: ['mandatory', 'today', 'tonight', 'tomorrow', 'held over', 'forced', 'no-?call no-?show', 'uncovered', 'still open', 'need(?:s|ed)? coverage', 'respond by', 'reply by', 'bids? (?:close|due)'],
    minImportance: 2,
    forceCategory: 'work',
    lineTemplate: '{subject} — {when} ({from})',
    sectionTitle: 'Shifts & overtime',
    promptHint: 'Shift changes, mandatory overtime, and bids with a deadline are actionable; put the shift date and time in the deadlines list.'
  },
  {
    id: 't-crops',
    name: 'Farm, weather & market notices',
    icon: '🌦️',
    description: 'Watches weather warnings, market and cash-bid reports, co-op and USDA notices, and farm program deadlines.',
    defaultFor: ['farmer'],
    match: [
      'crop insurance',
      'acreage report',
      '\\bfsa\\b',
      '\\busda\\b',
      '\\bnrcs\\b',
      'frost (?:warning|advisory)',
      'freeze warning',
      '\\bhail\\b',
      'drought',
      'flood warning',
      'red flag warning',
      'wind advisory',
      'cash bids?',
      'grain (?:prices?|contract|marketing|delivery)',
      'market (?:report|update|close|commentary)',
      'co-?op (?:notice|statement|patronage|meeting)',
      'patronage',
      'seed (?:order|delivery)',
      'fertilizer',
      'chemical (?:order|delivery)',
      'spray(?:ing)? (?:schedule|window)',
      'planting',
      'harvest',
      'calving',
      'weaning',
      'bull sale',
      'sale barn',
      'livestock auction',
      'vaccination',
      'water (?:allocation|delivery|order)',
      'irrigation (?:schedule|district)',
      'deadline (?:for|to) (?:enroll|sign-?up|report|certify)',
      'organic (?:certification|inspection)',
      'cash rent',
      'custom (?:harvest|hay|spray)'
    ],
    extractors: [
      { field: 'dueDate', pattern: `(?:deadline|due|by|before|enroll by|sign-?up by|certify by|report by|expires?) (?:is )?(?:on )?(${DATE})`, flags: 'i' },
      { field: 'price', pattern: '(\\$?\\d{1,3}(?:\\.\\d{2,4})?(?: ?/ ?| per )(?:bu|bushel|cwt|ton|lb|head|acre))', flags: 'i' },
      { field: 'amount', pattern: `(${MONEY})`, flags: 'i' }
    ],
    urgentWhen: ['frost', 'freeze', 'hail', 'tornado', 'red flag', 'flood', 'deadline (?:is )?(?:today|tomorrow|this week)', 'final (?:notice|day)', 'recall', 'quarantine', 'outbreak', 'avian (?:flu|influenza)', '\\bhpai\\b', 'foot and mouth', 'water (?:shut-?off|cut)', 'last day to'],
    minImportance: 2,
    forceCategory: 'work',
    lineTemplate: '{subject} — {price} due {dueDate} ({from})',
    sectionTitle: 'Farm, weather & markets',
    promptHint: 'Program sign-up and reporting deadlines always go in the deadlines list; weather warnings during planting or harvest and animal-disease notices are urgent.'
  }
]
