/**
 * Generates docs/PROFILES.md from the profile and skill catalogues.
 * Run: npm run docs:profiles
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { PROFILE_GROUPS, PROFILE_LIST } from '../src/main/profiles/profiles'
import { BUILTIN_SKILLS } from '../src/main/skills/library'

const skillName = (id: string): string => BUILTIN_SKILLS.find((s) => s.id === id)?.name ?? id

const lines: string[] = [
  '# Profiles — who InboxScout works for',
  '',
  `InboxScout tunes itself to the person: what counts as work mail, what is urgent, what the brief's rolling "pulse"`,
  'tracks, and which skills (watchers) are on. There are **' + PROFILE_LIST.length + ' built-in profiles** in five groups.',
  '',
  '**Choose for me** is on by default: after each scan InboxScout looks at what the mail is about and switches to the',
  'best-fitting profile when the evidence is clear (it only moves off a chosen profile on a high-confidence read, and',
  'never after you dismiss a suggestion). Pick one yourself in **Setup → Preferences** to lock it; choose',
  '*Let InboxScout figure it out* to hand it back. Other agents can do the same through the bridge',
  '(`list_profiles`, `detect_profile`, `set_profile`).',
  '',
  'Every profile still gets the universal skills (important people, bills, appointments…) and you can switch any',
  'skill on or off under **Setup → What to watch for**. Companies can add their own profiles and skills as JSON — see `docs/SKILLS.md`.',
  ''
]

for (const g of PROFILE_GROUPS) {
  const items = PROFILE_LIST.filter((p) => p.group === g.id)
  lines.push(`## ${g.icon} ${g.name} (${items.length})`, '', '| Profile | What it watches | Pulse | Default skills |', '|---|---|---|---|')
  for (const p of items) {
    lines.push(`| ${p.icon} **${p.name}** | ${p.tagline} | ${p.pulseName} | ${p.defaultSkills.map(skillName).join(', ')} |`)
  }
  lines.push('')
}

lines.push('## Skills that ship with the profiles', '', '| Skill | What it does |', '|---|---|')
for (const s of BUILTIN_SKILLS) lines.push(`| ${s.icon} **${s.name}** | ${s.description} |`)
lines.push('', '_Generated by `npm run docs:profiles` — edit the catalogues, not this file._', '')

const out = join(__dirname, '..', 'docs', 'PROFILES.md')
writeFileSync(out, lines.join('\n'), 'utf8')
console.log(`Wrote ${out}: ${PROFILE_LIST.length} profiles, ${BUILTIN_SKILLS.length} skills`)
